name: Build Docker Images for Prod & Push to DockerHub

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:

  build-and-deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker Build Backend
      run: |
        docker build . -t smirnovskoe/streamad_backend:prod
        
    - name: Docker Push Backend
      run: |
        docker push smirnovskoe/streamad_backend:prdo
